### PR TITLE
Refactor firmware sources

### PR DESCRIPTION
**Pull request by mathiasvr**
Attempt to simplify and make firmware definitions more generic.
Definitions of firmware versions and ESC layouts etc. is moved to the firmware classes and avoids need for specific structure and types at a later stage.
BLHeli firmware is split into a separate class for blheli_s/atmel/silabs variants.

### CODE REVIEW

**Comment by mathiasvr** [comment]
I ended up also removing the ability to fetch esc definitions remotely, but I can add it back if preferred.
The reason is that AM32 is already local to the configurator and i'm interested in moving the bluejay definitions here as well. BLHeli definitions is located at the blheli configurator repo, however they are not up to date and it PRs have gone stale in that repo, so it would be easier to maintain locally imo.

It's probably easier to look at the commits one by one because of the many changes. I have some additional changes/updates but will not include them yet as this PR is already getting too big.

**Comment by stylesuxx** [comment]
Hey, thank you - this clashes a bit with the changes I made, as it seems.

Regarding the definitions: I was hesitant to move them here, but if you say, that they are stale and you keep maintaining the bluejay definitions, I am all up for it. As you say, the AM32 definitions are here anyway.

I will see if I can cherry pick some of your commits, or how the merge goes in general.

**Comment by mathiasvr** [comment]
No problem, I can rebase the PR with your changes, would have been surprising if it didn't conflict at some point 😄

**Comment by stylesuxx** [comment]
Oh, wow - thanks :-)

**Comment by stylesuxx** [comment]
@mathiasvr I just pulled it in locally. From what I can see - remote fetching is now back and active. I think I will make a seperate issue for that and refactor it accordingly. Makes no sense to have that if we have the AM32 definitions locally and you maintain the Bluejay relevant ones here and BLHeliS is stale...

**Pull request merged**
