### PR TITLE
Use backdrop element to avoid closing dialog on drag

### PR DESCRIPTION
**Pull request by mathiasvr**
When doing mouse down inside the melody editor and dragging the mouse outside the editor and then releasing, the melody editor closes.
This could happen e.g. when selecting melody text with the mouse.

This fixes the issue, however now the editor is closed immediately on mousedown outside the editor. 
I think this is okay but it would be nice if it could be fixed with the `onClick` event.

### CODE REVIEW

**Comment by stylesuxx** [comment]
Thank you.

I have noticed this before, but opted to leave it as it is. I do not like the `onMouseDown` event, because I do not think it is semantically correct here (or in any application for that matter ) `onMouseDown` will trigger no matter which mouse button you press (left, middle, right). Further `onMouseDown` does not work properly on mobile devices, so we would need to handle the touch events separately.

I would rather prefer to only close the overlay when clicking the "X" instead of clicking outside the content of the overlay. I just think, that users are already conditioned in such a way, that they expect an overlay to close once clicking outside the content area.

**Comment by mathiasvr** [comment]
Ah yes, I will try if I can find a better way...

**Comment by mathiasvr** [comment]
How about this? I moved the backdrop to a different element that's not part of the click event chain.

**Comment by stylesuxx** [comment]
Yes, I like that - thank you! Looking at it, I am wondering if it would not make sense to have a small Overlay component - meldoy editor and settings could use the same logic then.

**Pull request merged**
