### PR TITLE
Update eslint, react-scripts and testing-library

### PR DESCRIPTION
**Pull request by mathiasvr**
Updates eslint and add some unused plugin/rules.

I changed some newly reported react hook/testing rules from errors to warnings because I didn't know how to fix them.

I had to update some react stuff as well because it wasn't happy with using new version as is.

### CODE REVIEW

**Comment by stylesuxx** [comment]
Alright - I was pushing this back and back...
I think we should probably update all dependencies then - updating some will already result in a big testing overhead so we might as well go full commit:

```
yarn outdated
yarn upgrade-interactive
```

Wanna have a go at it, or should I?

**Comment by mathiasvr** [comment]
If you update the dependencies I can probably squeeze this down to just the eslint updates I had in mind afterwards.

**Comment by stylesuxx** [comment]
Sounds like a plan!

**Comment by stylesuxx** [comment]
Alright - I updated everything. A big testing session is definitely in place after that, but I think you can add your changes against this branch: https://github.com/stylesuxx/esc-configurator/tree/dependency-update

Unfortunately the newest version of the highlighter for the melody editor is buggy (https://github.com/bonafideduck/react-highlight-within-textarea/issues/85) and the previous version is not compatible with the newest react version. I might give the library a poke later this weekend and see if I can get a PR going.

**Comment by stylesuxx** [comment]
Alright, I took your style adaptations and also integrated them into https://github.com/stylesuxx/esc-configurator/tree/dependency-update

The higlighter has also been fixed in the mean time. I should have everything from this PR covered in my branch, that's why I will close this PR and merge the other branch into develop.

**Pull request closed without merging**
