### PR TITLE
Fetch version list from github releases

### PR DESCRIPTION
**Pull request by mathiasvr**
I'm experimenting with getting the version list from github releases api since it would be nice not to maintain a separate list.

It's not ready yet but mostly works. Thoughts? 😉

### CODE REVIEW

**Comment by stylesuxx** [comment]
Yes, I very much like this - do you know if this would work with BLHeli_S too?
Would definetly prefer to use API's wherever possible, so this change is very welcome.

Only added one comment to override the implementing Source Class for Bluejay instead of having if's in the base class. I could also imagine a "Github Source" Class that extends the Source Class and which is then used by the BluejaySource class - then the code might easily be reused for BLHeli_S or even AM32.

**Comment by mathiasvr** [comment]
Okay sounds great, should work for AM32 as well.

**Comment by stylesuxx** [comment]
@mathiasvr I am thinking about releasing a new version in the coming days and was wondering if anything is missing here, or if I can help in any way to get this PR out of the draft state?
Am not meaning to stress, was just wondering if I should wait or if this will be part of a different release.

**Comment by mathiasvr** [comment]
I been working on some changes/cleanup to make this pr a bit simpler, but it went a bit out of control so now i have a bit more work to do before it works lol. We could probably merge this as it is, but I think it would be fine to wait for a different release?

**Comment by stylesuxx** [comment]
Alright, totally fine with me.

**Comment by mathiasvr** [comment]
I had some problems with the unit tests but at least it works now. The mock's can probably be improved.

Do we need to use the cors proxy for github api? It might be better to request directly to avoid rate limiting.

**Comment by mathiasvr** [comment]
Also to explain the changes a bit:

A list of releases is requested through the github rest api and I made the fetch calls cache responses for 24 hours using the browsers CacheStorage. This reduces the number of requests which can take a while to process, especially the bluejay releases with many assets.
I also added a setting to show or hide github pre-releases.

**Comment by stylesuxx** [comment]
> Do we need to use the cors proxy for github api? It might be better to request directly to avoid rate limiting.

Unfortunately yes - github is blocked (for example) in China - this is a "cheap" way to circumvent this block.

> This reduces the number of requests which can take a while to process, especially the bluejay releases with many assets.

Could you quantify "a while"? Do you think it would make sense to run  a dedicated wrapper API to cache those queries - maybe with a cronjob which updates once overy 2h or so? Is this a public API - any idea about rate limits?

**Comment by mathiasvr** [comment]
Ah okay, maybe proxy should be a setting? 

Well it only takes a few seconds but enough to make it hang a bit. I think it's fine to just cache it like this, the firmware versions won't update very often. Of course since it's using a proxy now it could also be cached there, but I think we need this for offline mode anyway so should be fine.

**Comment by stylesuxx** [comment]
The proxy has a 2nd function too which is essential for file delivery - we are using it to bypass CORS errors when fetching the firmware files - so I can't really make it optional.

I hope I can find some time this week to give it an actual try - maybe I am missing something by looking at the code, but I am not thrilled that we have to let the user wait a couple of seconds every time he accesses the page (at least after 24h have passed).

Maybe this can be done in an async way - the user needs some time anyway to click through to the flashing screen - this should be enough time to fetch the version data in the background.

**Comment by mathiasvr** [comment]
I think GitHub has correct cors permissions?

Yes I think the versions can be updated async, I just kept the current sync behavior, I can try updating it and see if there are any problems.

**Comment by stylesuxx** [comment]
> I think GitHub has correct cors permissions?

Yes it does, that's the problem ;-) If a user tries to fetch a file via esc-configurator.com, github will complain because it's a cross origin request. You don't have that when fetching from localhost.

Would be great if you could look into async updates - if you have the motivation.

**Comment by mathiasvr** [comment]
Hmm wasn't as simple as I hoped but seemed to make it work with this: https://github.com/mathiasvr/esc-configurator/commit/a18870fb101a2d29e2842bd68aa6ddb023e127d4

Not sure if that's the best way, but also I couldn't figure out the prop types and how to fix the tests 😞

**Comment by stylesuxx** [comment]
That does not look too bad - thank you. I would probably have solved it by initially passing an empty config object and only updating it once `fetchConfigs` finished - basically settings the configs state at the end of `fetchConfigs` or using `then` on the `fetchConfigs` function:

```javascript
fetchConfigs().then((configs) => {
    this.setState({ configs });
});
```
from what I can see you basically do the same anyway just that your then is somewhere else...

Can you push your changes to this PR please? Then I will poke around a bit and get the tests going.

**Comment by mathiasvr** [comment]
That sounds much better, I think you can just do that and disregard my changes as I think they will not be necessary that way.

**Comment by stylesuxx** [comment]
Alright - then I will merge your changes later on.
Thanks!

**Pull request merged**
